[platformio]
default_envs = esp32doit-devkit-v1
src_dir = firmware/boot/src

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Libraries
lib_deps =
    ArduinoJson @ ^6.21.0

; Serial & Upload
upload_speed = 460800
monitor_speed = 115200
upload_port = /dev/cu.usbserial-110
monitor_filters = esp32_exception_decoder

; Include paths for application module headers
build_flags =
    -DARDUINO_LOG_LEVEL=4
    -Ifirmware/appl/led/inc
    -Ifirmware/appl/wifi/inc
    -Ifirmware/appl/image/inc
    -Ifirmware/appl/ocr/inc
    -Ifirmware/appl/comm/inc

; Pull in application module source files
build_src_filter =
    +<*>
    +<../../../firmware/appl/led/src/>
    +<../../../firmware/appl/wifi/src/>
    +<../../../firmware/appl/image/src/>
    +<../../../firmware/appl/ocr/src/>
    +<../../../firmware/appl/comm/src/>
